metric: average_precision_score

timeout: ${eval:'60*60*12'} #60*60*6
cpu_limit: 16
memory_limit: 128

reader_params:
  n_jobs: 16

tuning_params:
  'max_tuning_time': 1800   
  'max_tuning_iter': 200

# general_params:
#   use_algos:
#     - [linear_l2, lgb, lgb_tuned, cb, cb_tuned, rf, rf_tuned, xgb, xgb_tuned, nn]
#     - [lgb, cb]
