n_jobs: 16
scorer: roc_auc_score
scorer_type: soft
# pipeline:
#   scaler: preprocessing.StandardScaler
#   clf: ensemble.GradientBoostingClassifier
# grid_search_params:
#   clf__random_state:
#     - 42
#   clf__learning_rate:
#     - 0.1
#   clf__n_estimators:
#     - 50
#     - 100
#     - 500
#     - 1000
#   clf__max_depth:
#     - 3
#     - 10
#     - 50
#   clf__min_samples_leaf:
#     - 1
#     - 5
#     - 10
#     - 50

# gs_extrapolation_max_attempts: 100
# gs_extrapolation_params:
#   clf__learning_rate:
#     scale: log
#     step: 10
#     min: 0.0001
#     max: 1
#   clf__n_estimators:
#     scale: log
#     step: 10
#     min: 1
#     max: 10000
#   clf__max_depth:
#     scale: log
#     step: 10
#     min: 1
#     max: 100
#   clf__min_samples_leaf:
#     scale: log
#     step: 10
#     min: 1
#     max: 1000